include $(GOROOT)/src/Make.inc

TARG=feyeleanor/golightly/vm
GOFILES=\
	utility.go\
	instruction_set.go\
	buffer.go\
	vector.go\
	iocontroller.go\
	processor_core.go\
	program.go\

include $(GOROOT)/src/Make.pkg