include $(GOROOT)/src/Make.$(GOARCH)

TARG=feyeleanor/golightly/vm
GOFILES=\
	instruction_set.go\
	buffer.go\
	vector.go\
	iocontroller.go\
	processor_core.go\
	program.go\

include $(GOROOT)/src/Make.pkg